@startuml
class Address
Address --> Adder
Address --> Memory
Adder --> "IF/ID"
Memory --> "IF/ID"
"IF/ID" --> "ID/EX"
"IF/ID" --> "Reg File"
"IF/ID" --> "Reg File"
"IF/ID" --> "Sign Extend"
"IF/ID" --> "ID/EX"
"ID/EX" --> MUX --> ALU
"ID/EX" --> MUX --> ALU
@enduml
